tz diploma ep2
babkaizergil/java-explore-with-me pull request #4
Opened 2023-08-25 17:23 UTC by babkaizergil

Доброе время суток!
Основной сервис согласно ТЗ

2023-08-28 16:58 UTC, Donald522 requested changes
Привет!

В целом все хорошо, написал пару небольших замечаний

2023-08-28 16:58 UTC, Donald522 commented on main-server/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +        log.info("Delete category request.");
В лог надо обязательно добавить id который удаляем

2023-08-28 16:58 UTC, Donald522 commented on main-server/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        Category categoryByName = categoryRepository.findByName(newCategoryDto.getName());
Если мы обновляем по id, то зачем доставать по имени и делать проверку на id?
Это неочевидное поведение.
Лучше достать по id и обновить

2023-08-29 11:32 UTC, babkaizergil commented on main-server/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +    public void deleteCategory(@PathVariable Long catId) {
Ок, исправлено. Но. Название взято из спецификации API основного сервиса.

2023-08-29 12:28 UTC, babkaizergil commented on main-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS events
полагаю что оптимальным будет добавить индексы на столбцы event_Date, initiator_id и category_id, так как они чаще всего фигурируют у меня в запросах. добавила.

2023-08-29 12:40 UTC, babkaizergil commented on main-server/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        Category categoryByName = categoryRepository.findByName(newCategoryDto.getName());
исправила

2023-08-29 12:43 UTC, babkaizergil commented
Приветствую, Антон! Учла твои замечания.

2023-08-29 13:22 UTC, babkaizergil commented on main-server/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        Category categoryByName = categoryRepository.findByName(newCategoryDto.getName());
это ветвление нужно, чтобы проверить, что имя категории не меняется на то же самое имя или на уже занятое. есть два теста, проверяющих это поведение и ожидающих исключение. поэтому с твоего согласия, я оставлю как есть.

2023-08-29 20:06 UTC, Donald522 approved these changes

2023-08-30 05:07 UTC, merged